# Generated by Django 6.0.1 on 2026-01-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_taskassignment_is_completed_alter_campaign_project_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
