# Generated by Django 5.0.1 on 2026-04-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_dm_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='test_case',
        ),
    ]
