# Generated by Django 5.0.1 on 2026-05-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_remove_comment_test_case'),
        ('testCases', '0005_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testCases.testcase'),
        ),
    ]
