# Generated by Django 5.0.1 on 2026-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproject',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINÉ', 'Terminé')], default='ACTIF', max_length=20),
        ),
    ]
