# Generated by Django 6.0.1 on 2026-01-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
        ('testCases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='testCases.testcases'),
        ),
    ]
