# Generated by Django 6.0.1 on 2026-01-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='preuve_image',
            field=models.ImageField(blank=True, null=True, upload_to='anomalies/preuves/%Y/%m/%d/'),
        ),
    ]
