# Generated by Django 6.0.1 on 2026-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0003_anomalie_preuve_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='preuve_image',
            field=models.FileField(blank=True, null=True, upload_to='anomalies/preuves/%Y/%m/%d/'),
        ),
    ]
