# Generated by Django 5.0.1 on 2026-04-01 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0004_alter_anomalie_preuve_image'),
        ('testCases', '0004_testcase_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='testCases.testcase'),
        ),
    ]
