# Generated by Django 5.0.1 on 2026-04-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0005_alter_anomalie_test_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='statut',
            field=models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_INVESTIGATION', 'En investigation'), ('RESOLUE', 'Résolue')], default='OUVERTE', max_length=20),
        ),
    ]
