# Generated by Django 5.0.1 on 2026-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0006_anomalie_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='criticite',
        ),
        migrations.AddField(
            model_name='anomalie',
            name='impact',
            field=models.CharField(choices=[('FONCTIONNALITE', 'Fonctionnalité'), ('SIMPLE', 'Simple'), ('TEXTE', 'Texte'), ('COSMETIQUE', 'Cosmétique'), ('MINEURS', 'Mineurs'), ('MAJEUR', 'Majeur'), ('CRITIQUE', 'Critique'), ('BLOQUANTES', 'Bloquantes')], default='MINEURS', max_length=20),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='priorite',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('BASSE', 'Basse'), ('ELEVEE', 'Élevée'), ('URGENTE', 'Urgente'), ('IMMEDIATE', 'Immédiate')], default='NORMALE', max_length=20),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='visibilite',
            field=models.CharField(choices=[('PUBLIQUE', 'Publique'), ('PRIVEE', 'Privée')], default='PUBLIQUE', max_length=20),
        ),
    ]
