# Generated by Django 5.0.1 on 2026-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0007_remove_anomalie_criticite_anomalie_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='preuve_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
