# Generated by Django 5.0.1 on 2026-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0008_anomalie_preuve_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='impact',
            field=models.CharField(choices=[('A_DEFINIR', 'À définir'), ('FONCTIONNALITE', 'Fonctionnalité'), ('SIMPLE', 'Simple'), ('TEXTE', 'Texte'), ('COSMETIQUE', 'Cosmétique'), ('MINEURS', 'Mineurs'), ('MAJEUR', 'Majeur'), ('CRITIQUE', 'Critique'), ('BLOQUANTES', 'Bloquantes')], default='A_DEFINIR', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='priorite',
            field=models.CharField(choices=[('A_DEFINIR', 'À définir'), ('NORMALE', 'Normale'), ('BASSE', 'Basse'), ('ELEVEE', 'Élevée'), ('URGENTE', 'Urgente'), ('IMMEDIATE', 'Immédiate')], default='A_DEFINIR', max_length=20),
        ),
    ]
