# Generated by Django 5.0.1 on 2026-06-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0009_alter_anomalie_impact_alter_anomalie_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='preuve_video',
            field=models.FileField(blank=True, null=True, upload_to='anomalies/videos/%Y/%m/%d/'),
        ),
    ]
