# Generated by Django 5.0.1 on 2026-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_features_project_gantt_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('PLANNING', 'Planifié'), ('COMPLETED', 'Terminé')], default='ACTIVE', max_length=20),
        ),
    ]
