# Generated by Django 5.0.1 on 2026-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
