# Generated by Django 5.0.1 on 2026-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_project_planned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='planned_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('PLANNING', 'Planifié'), ('COMPLETED', 'Terminé')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
