# Generated by Django 5.0.1 on 2026-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_project_planned_date_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='planned_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('PLANNING', 'Planifié'), ('COMPLETED', 'Terminé')], default='ACTIVE', max_length=20),
        ),
    ]
