# Generated by Django 5.0.1 on 2026-04-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_remove_project_planned_date_alter_project_status'),
        ('business_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='business_projects.businessproject', verbose_name='Projet Parent'),
        ),
        migrations.AddField(
            model_name='project',
            name='release_type',
            field=models.CharField(choices=[('PREPROD', 'Préproduction'), ('RECETTE', 'Recette')], default='RECETTE', max_length=20, verbose_name='Type de Release'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_releases', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
