# Generated by Django 5.0.1 on 2026-04-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_project_business_project_project_release_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gantt_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
