# Generated by Django 5.0.1 on 2026-04-18 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_remove_project_features_remove_project_gantt_data_and_more'),
        ('business_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='business_projects.businessproject', verbose_name='Projet Parent'),
        ),
    ]
