# Generated by Django 6.0.1 on 2026-01-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_taskassignment_is_completed_alter_campaign_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_ref', models.CharField(max_length=100)),
                ('data_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PASSED', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='campaigns.campaign')),
            ],
        ),
    ]
