# Generated by Django 6.0.1 on 2026-01-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0002_initial'),
        ('campaigns', '0003_taskassignment_is_completed_alter_campaign_project_and_more'),
        ('testCases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
