# Generated by Django 6.0.1 on 2026-02-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCases', '0003_testcase_execution_date_testcase_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='executions/proofs/%Y/%m/%d/'),
        ),
    ]
