# Generated by Django 5.0.1 on 2026-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCases', '0004_testcase_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('PASSED', 'Succès'), ('FAILED', 'Échec')], default='PASSED', max_length=20),
        ),
    ]
