# Generated by Django 5.0.1 on 2026-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCases', '0005_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='automation_code',
            field=models.TextField(blank=True, help_text="Code Playwright généré par l'IA", null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='automation_script_path',
            field=models.CharField(blank=True, help_text='Chemin physique du script .py/.ts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='Vrai si ce test a vocation à être automatisé'),
        ),
    ]
