# Generated by Django 5.0.1 on 2026-06-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCases', '0006_testcase_automation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='proof_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
