# Generated by Django 5.0.1 on 2026-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCases', '0007_testcase_proof_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'À faire'), ('PASSED', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=20),
        ),
    ]
