# Generated by Django 5.0.1 on 2026-06-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCases', '0008_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='proof_video',
            field=models.FileField(blank=True, null=True, upload_to='executions/videos/%Y/%m/%d/'),
        ),
    ]
