@startuml
autonumber
skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Administrateur" as A
participant "Interface (React)" as F
participant "API (Django)" as B
database "Base de Données" as DB

title CRUD : Gestion des Projets & Releases

== Création Projet Business (Niveau 1) ==
A -> F : Valider formulaire Nouveau Projet Business
F -> B : POST /api/business-projects/
B -> DB : Sauvegarder l'entité
B --> F : 201 Créé

== Création Release / Projet (Niveau 2) ==
A -> F : Valider formulaire Nouvelle Release
F -> B : POST /api/projects/ (FK: projet_business, type)
B -> DB : Sauvegarder la release liée
B --> F : 201 Créé
@enduml
