@startuml
autonumber
skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Testeur" as T
participant "Interface (React)" as F
participant "API (Django)" as B
database "Base de Données" as DB

title CRUD : Création d'une Anomalie

T -> F : Cliquer sur "Signaler une anomalie"
F -> B : GET /api/anomalies/meta/ (Impacts/Priorités)
B --> F : Liste des Choix
T -> F : Saisir Titre, Description, Impact, Priorité + Témoin (Image)
F -> B : POST /api/anomalies/ (Multipart/Data)
B -> B : Valider les métadonnées
B -> DB : Insérer l'Anomalie liée au Cas de Test
B -> B : Déclencher le flux de notification
B --> F : 201 Créé (ID Anomalie)
F --> T : Confirmation & Mise à jour de la grille
@enduml
