@startuml
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur (Abstrait)" as User
actor "Administrateur" as Admin
actor "Manager QA" as Manager
actor "Testeur" as Tester

' Systèmes Externes
actor "Serveur SMTP" as SMTP <<System>>
actor "API Groq (LLM)" as AI <<System>>

' Héritage
User <|-- Admin
User <|-- Manager
User <|-- Tester

rectangle "InsureTM - Plateforme d'Orchestration de Tests" {

  ' --- Authentification ---
  package "Authentification" {
      usecase "S'authentifier (Login SSO/JWT)" as Login
      usecase "Gérer son Profil" as Profile
  }
  User --> Login
  User --> Profile

  ' --- Administration ---
  package "Administration" {
      usecase "Gérer les Utilisateurs (RBAC)" as UC1
      usecase "Gérer les Projets & Config" as UC2
  }
  Admin --> UC1
  Admin --> UC2

  ' --- Gestion des Tests ---
  package "Gestion des Tests" {
      usecase "Gérer le Référentiel de Tests" as UC3
      usecase "Planifier des Campagnes" as UC4
      usecase "Assigner des Testeurs" as UC5
      UC4 ..> UC5 : <<include>>
      UC4 ..> Login : <<include>>
  }
  Manager --> UC3
  Manager --> UC4
  UC3 ..> Login : <<include>>

  ' --- Exécution ---
  package "Exécution & Qualité" {
      usecase "Exécuter les Tests (Runner)" as UC6
      usecase "Signaler une Anomalie" as UC7
      UC7 .> UC6 : <<extend>>
  }
  Tester --> UC6
  Tester --> UC7
  UC6 ..> Login : <<include>>
  UC7 ..> Login : <<include>>

  ' --- Reporting & IA ---
  package "Reporting & IA" {
      usecase "Suivre l'Avancement (Dashboard)" as UC8
      usecase "Interroger Assistant IA (NL-to-SQL)" as UC9
      usecase "Reformuler Message (IA)" as UC10
      usecase "Recevoir Notifications" as UC11
  }
  
  ' Liens Transverses
  Admin --> UC8
  Manager --> UC8
  Manager --> UC9
  Tester --> UC8
  Tester --> UC10

  UC8 ..> Login : <<include>>
  UC9 ..> Login : <<include>>
  UC10 .> UC7 : <<extend>>

  ' Systèmes Externes
  UC11 -- SMTP
  UC9 -- AI
  UC10 -- AI
  UC4 ..> UC11 : <<include>>
  UC7 ..> UC11 : <<include>>

}
@enduml
