# Generated by Django 6.0.1 on 2026-01-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('campaigns', '0002_remove_campaign_manager_campaign_assigned_testers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='Project.project'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.campaign'),
        ),
    ]
