# Generated by Django 6.0.2 on 2026-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_description_campaign_imported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
