# Generated by Django 6.0.2 on 2026-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_estimated_end_date_campaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='excel_file',
            field=models.FileField(blank=True, upload_to='campaigns/referentiels/%Y/%m/%d/'),
        ),
    ]
