# Generated by Django 5.0.1 on 2026-04-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_scheduled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_processed',
        ),
    ]
