# Generated by Django 5.0.1 on 2026-04-29 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_remove_campaign_assigned_testers_campaignassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='assigned_testers',
            field=models.ManyToManyField(blank=True, related_name='assigned_campaigns', through='campaigns.CampaignAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
